#!/bin/bash
set -exo pipefail
RUBY_VERSION=${RUBY_VERSION:-2.0.0}

function set_environment() {
  WORKSPACE=${WORKSPACE:-.}

  ruby_version=$1
  if [ -e "$HOME/.rvm/scripts/rvm" ]; then
    source  "$HOME/.rvm/scripts/rvm"
    rvm use $RUBY_VERSION
  elif [ -e /usr/local/rvm/scripts/rvm ]; then
    source /usr/local/rvm/scripts/rvm
    rvm use $RUBY_VERSION
  else
    echo "Going ahead with system Ruby `ruby -v`"
  fi

  export LANG=en_US.UTF-8
  export LC_CTYPE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
}

set_environment $RUBY_VERSION

bundle $@
