#!/bin/bash
source $(dirname $0)/_bundle

function set_database_yml() {
  if [ -e $WORKSPACE/config/database.deployment.yml ] && [ ! -e $WORKSPACE/config/database.yml ]; then
    cp $WORKSPACE/config/database{.deployment,}.yml
  fi
}

function set_default_environment_config() {
  if [ -e $WORKSPACE/.env.example ] && [ ! -e $WORKSPACE/.env ]; then
    cp $WORKSPACE/.env{.example,}
  fi
}

set_database_yml
set_default_environment_config

bundle install
bundle exec rake $@
