#!/bin/bash
source $(dirname $0)/_bundle

function set_database_yml() {
  if [ -e $WORKSPACE/config/database.deployment.yml ] && [ ! -e $WORKSPACE/config/database.yml ]; then
    cp $WORKSPACE/config/database{.deployment,}.yml
  fi
}

set_database_yml

bundle install
bundle exec rake $@
